### ISSUE TITLE
Feature request: SSL cert fingerprint pinning

### ISSUE THREAD

**Issue by Leseratte10** [LukasK32/fleeting-plugin-proxmox#11]
Thanks for the great plugin!

My Proxmox node doesn't have a globally trusted certificate from a CA, and instead just uses the Proxmox default self-created CA. This means I need the "insecure_skip_tls_verify" parameter. 

Could you add another parameter that allows the user to specify the fingerprint of a trusted CA or server certificate? That way I could just enter the Proxmox CA fingerprint into the plugin config and still be sure that the connection to Proxmox is secure.
And/or a path to a folder of trusted certificates / CAs so I could make this plugin trust a certain CA / certificate without having to add it to the system trust store.

**Comment by jyoung-ics** [comment]
Would this not be dependent on the host OS (where the plugin is running)? Maybe try adding the CA to the runner host OS certificate store. 

I have no idea if this will actually work but it's worth a try!

**Comment by Leseratte10** [comment]
Yes and no. 

Yes, by default this will use the CA certificate store of the host. The issue is that if I add the Proxmox-self-generated CA to my host's certificate store, it won't just be trusted for communications with Proxmox, it would be trusted for any communications. 

Meaning if an attacker gets access to that CA they can MITM all my traffic without me noticing. 
If this plugin itself had a feature to select a custom CA or cert to trust, then that would make sure that the Proxmox CA is only trusted for connections _to the Proxmox server_ and not to any others.

**Comment by LukasK32** [comment]
You can try setting up `SSL_CERT_FILE` and `SSL_CERT_DIR` as documented here: [link](https://pkg.go.dev/crypto/x509#SystemCertPool), I guess that this pool is used by default but I'm not sure

**Comment by Leseratte10** [comment]
Thanks, that's working. Didn't know Go had something like that. I guess that means the additional config parameter is no longer needed.
